### ISSUE TITLE
Exiting Luxray overlay doesn't return to Tesla menu

### ISSUE THREAD

**Issue by DiscostewSM** [3096/luxray#1]
This is mainly because Tesla had undergone some changes. Other overlays produce the same kind of result. Didn't see any issue when loading Luxray from the Tesla menu, but exiting simply makes the overlay disappear when it would originally return to the Tesla menu.

**Comment by 3096** [comment]
It's only supposed to return to Tesla Menu when it's loaded from Tesla Menu. Otherwise Luxray runs as its own sysmodule. From your description it sounds like it's working as intended?

**Comment by DiscostewSM** [comment]
Maybe I didn't explain it well enough, so let me show you.

Luxray prior to the update - https://youtu.be/Kw0jPDRjyNA
Luxray after the update - https://youtu.be/C2JJ2l9IDJw

Added bonus

CaptureSight after the update - https://youtu.be/PIXWKhy2wbg

**Comment by 3096** [comment]
Oh looks like I misunderstood. I'll look into the issue.
